package com.cts.inward.enums;

public enum WorkflowStatus {
    RECEIVED, PARSED, AVAILABLE_FOR_MAKER, MAKER_LOCKED, MAKER_PROCESSING, MAKER_REPAIRED, SENT_TO_CHECKER, CHECKER_LOCKED, CHECKER_PROCESSING, RETURNED_TO_MAKER, CHECKER_VERIFIED, CBS_VALIDATION, ACCEPTED, REJECTED
}
