inward.root.path=C:/Users/Documents/CTS_Integration/CTS/inward-files

inward.file.processing.thread.pool.size=4

db.driver.class=org.postgresql.Driver
db.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
db.username=postgres.bijnscklhxftxritxdrc
db.password=Sushmabandari@123