inward.root.path=~/Desktop/ws_iispl022026ZK/CTS/inward-chi-files

inward.file.processing.thread.pool.size=4

db.driver.class=org.postgresql.Driver
db.url=jdbc:postgresql://db.bijnscklhxftxritxdrc.supabase.co:5432/postgres
db.username=postgres
db.password=Sushmabandari@123